package com.example.recyclerviewexampleviews

class ElementoProvider {
    companion object {
        val Elemento = listOf<Elementos>(
            Elementos("Primero",
                "https://dealgoritmos.com/wp-content/uploads/2023/05/6d8841b6-9d24-457a-95c5-0d3de1d7bf5f.png",
                "1"),
            Elementos("Segundo",
                "https://media.istockphoto.com/id/1367357589/es/foto/cielo-rojo-en-forma-de-coraz%C3%B3n-al-atardecer-hermoso-paisaje-con-flores-me-encanta-el-fondo-con.jpg?s=612x612&w=0&k=20&c=A2u-PoF7LGHvwhjf3_CRziNxK-Zh8tiRFjl7i7M2Gv4=",
                "2"),
            Elementos("Tercero",
                "https://images.unsplash.com/reserve/Af0sF2OS5S5gatqrKzVP_Silhoutte.jpg?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8fA%3D%3D&w=1000&q=80",
                "3"),
            Elementos("Cuarto",
                "https://previews.123rf.com/images/bahtiarmaulana/bahtiarmaulana2204/bahtiarmaulana220400040/185159316-rebanada-de-dibujos-animados-de-pizza-ilustraci%C3%B3n-de-dibujos-animados-vectoriales-im%C3%A1genes.jpg",
                "4"),
            Elementos("Quinto",
                "https://i.blogs.es/0ca9a6/aa/1366_2000.jpeg",
                "5"),
            Elementos("Sexto",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN72Tin8kLxpN4kzEgr5YCgzOFaxer3AVOGQ",
                "6"),
            Elementos("Septimo",
                "https://img.freepik.com/vector-premium/imagenes-predisenadas-dia-mundial-medio-ambiente-ilustracion-vectorial-ninos_491934-934.jpg",
                "7"),
            Elementos("Octavo",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyQh5g9ZRjOlonwUfjVXkn0rBY8AQ2uNw0CQ",
                "8"),
            Elementos("Noveno",
                "https://previews.123rf.com/images/shushanto/shushanto2209/shushanto220900703/191842443-imagen-de-fondo-de-la-ilustraci%C3%B3n-del-arte-conceptual-de-la-destrucci%C3%B3n-de-los-planetas.jpg",
                "9"),
            Elementos("Decimo",
                "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTISxnOdLgD7id3Oj-7jUUqZg8ycdKxtno9cQ",
                "10"),
            Elementos("Onceavo",
                "https://st.depositphotos.com/1016440/2534/i/450/depositphotos_25344733-stock-photo-sunrise-at-the-beach.jpg",
                "11"),
            Elementos("Doceavo",
                "https://letraslibres.com/wp-content/uploads/2016/05/barba_01_600_pix_0.jpg",
                "12"),
            Elementos("Decimo tercero",
                "https://www.educaciontrespuntocero.com/wp-content/uploads/2019/02/girasoles.jpg",
                "13"),
            Elementos("Decimo cuarto",
                "https://images.pexels.com/photos/2486168/pexels-photo-2486168.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                "14")
        )
    }
}